"""
Django settings for rozert_pay project.

Generated by 'django-admin startproject' using Django 4.0.10.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import logging
import os
import sys
import typing as ty
from os import getenv
from pathlib import Path

from django.utils.functional import cached_property
from dotenv import load_dotenv

from . import get_secrets_value

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_ROOT = BASE_DIR.parent
PROJECT_COMMON_ROOT = PROJECT_ROOT / "common"

PROJECT_COMMON_ROOT = BASE_DIR / "../common"


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-haxf()&@o0jp&dmu-c9=q$bugrsm)ss(eel)1%mnq(zw@duvf$"

# SECURITY WARNING: don't run with debug turned on in production!
_DEBUG = os.environ.get("DEBUG", "True")
DEBUG = _DEBUG.lower() in ("true", "1", "yes", "t", "y")

DEBUG = False
ALLOWED_HOSTS: list[str] = ["*"]


AUTH_USER_MODEL = "account.User"

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_extensions",
    "whitenoise",
    "rest_framework",
    "drf_spectacular",
    "django_object_actions",
    "django_json_widget",
    "django_celery_beat",
    "auditlog",
    "rozert_pay.payment",
    "rozert_pay.account",
]

MIDDLEWARE = [
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "rozert_pay.common.middlewares.LogResponseMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "auditlog.middleware.AuditlogMiddleware",
]

ROOT_URLCONF = "rozert_pay.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "rozert_pay/limits/templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "rozert_pay.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": os.environ.get("POSTGRES_DATABASE", "development"),
        "USER": os.environ.get("POSTGRES_USER", "development"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "JONH_DOE"),
        "HOST": os.environ.get("POSTGRES_HOST", "localhost"),
        "PORT": int(os.environ.get("POSTGRES_PORT", "5432")),
    },
}

REDIS_PASSWORD = get_secrets_value("REDIS_PASSWORD", getenv("REDIS_PASSWORD", ""))

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://{os.environ.get('REDIS_HOST', 'localhost')}:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "PASSWORD": REDIS_PASSWORD,
        },
    },
}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [
    BASE_DIR / "front/build",
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


RABBITMQ_HOST = os.environ.get("RABBITMQ_HOST", "localhost")
RABBITMQ_USER = os.environ.get("RABBITMQ_USER", "development")
RABBITMQ_PASSWORD = os.environ.get("RABBITMQ_PASSWORD", "development")
CELERY_BROKER_URL = f"amqp://{RABBITMQ_USER}:{RABBITMQ_PASSWORD}@{RABBITMQ_HOST}:5672//"
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True


USE_JSON_LOGGING = os.environ.get("USE_JSON_LOGGING", False)


LOGGING: dict[str, ty.Any] = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "default": {
            "()": logging.Formatter,
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "default",
            "level": "NOTSET",
        },
    },
    "loggers": {
        "": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": True,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

if getenv("DJANGO_QUERY_LOG"):
    LOGGING["loggers"]["django.db.backends"] = {
        "handlers": ["console"],
        "level": "DEBUG",
        "propagate": False,
    }


_IS_PRODUCTION = os.environ.get("IS_PRODUCTION", "False")
IS_PRODUCTION = _IS_PRODUCTION.lower() in ("true", "1", "yes", "t", "y")

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}


SPECTACULAR_SETTINGS = {
    "TITLE": "Rozert Pay",
    "DESCRIPTION": "Rozert Payment API",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}


SENTRY_DSN = os.environ.get("SENTRY_DSN", None)

EXTERNAL_ROZERT_HOST = "https://development.com"

IS_UNITTESTS = False

if IS_PRODUCTION:
    BETMASTER_BASE_URL = "https://development.com/"
else:
    BETMASTER_BASE_URL = "https://development.com/"

SLACK_TOKEN = os.environ.get("SLACK_TOKEN", None)
SLACK_UNEXPRECTED_NOTIFY_CHANNEL = "#development"

try:
    from .local_settings import *  # type: ignore[import-untyped] # noqa
except ImportError:
    pass


# Disable DRF Browsable API in non-debug environments
if not DEBUG:
    REST_FRAMEWORK["DEFAULT_RENDERER_CLASSES"] = (  # type: ignore[assignment]
        "rest_framework.renderers.JSONRenderer",
    )
