# Generated by Django 5.2.9 on 2025-12-04 10:26

import django.contrib.postgres.fields
import django.db.models.deletion
import rozert_pay.payment.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=300)),
                (
                    "is_non_bank",
                    models.BooleanField(
                        default=False,
                        verbose_name="Other licensed financial institution",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bank",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="CurrencyWallet",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("currency", models.CharField(max_length=3)),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "hold_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "operational_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total funds, including confirmed and pending.",
                        max_digits=15,
                    ),
                ),
                (
                    "frozen_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Part of operational_balance that is temporarily locked.",
                        max_digits=15,
                    ),
                ),
                (
                    "pending_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Part of operational_balance that is awaiting settlement from a provider.",
                        max_digits=15,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("external_id", models.CharField(max_length=255, unique=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=255, null=True)),
                ("language", models.CharField(blank=True, max_length=10, null=True)),
                ("extra", models.JSONField(blank=True, default=dict)),
                (
                    "risk_control",
                    models.BooleanField(
                        default=False,
                        help_text="If True, Risk Limits will be checked for this customer",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PaymentSystem",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "slug",
                    models.CharField(
                        blank=True, max_length=200, null=True, unique=True
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("d24_mercadopago", "D24 MercadoPago")], max_length=200
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "deposit_allowed_ttl_seconds",
                    models.PositiveIntegerField(
                        default=172800,
                        help_text="Time to live for deposit transactions. Initial transactions longer than this will be failed with decline code 'Too long execution'.",
                    ),
                ),
                (
                    "withdrawal_allowed_ttl_seconds",
                    models.PositiveIntegerField(
                        default=86400,
                        help_text="Time to live for withdrawal transactions. Initial transactions longer than this will be failed with decline code 'Too long execution'.",
                    ),
                ),
                (
                    "ip_whitelist",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("ip_whitelist_enabled", models.BooleanField(default=True)),
                ("client_request_timeout", models.FloatField(default=30)),
                (
                    "callback_secret_key",
                    models.CharField(
                        blank=True,
                        help_text="Secret key for callbacks from payment system",
                        max_length=200,
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CustomerCard",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("unique_identity", models.CharField(max_length=200)),
                ("card_data", models.JSONField(default=dict)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payment.customer",
                    ),
                ),
            ],
            options={
                "unique_together": {("unique_identity", "customer")},
            },
        ),
        migrations.CreateModel(
            name="CustomerDepositInstruction",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "system_type",
                    models.CharField(
                        choices=[("d24_mercadopago", "D24 MercadoPago")], max_length=200
                    ),
                ),
                (
                    "deposit_account_number",
                    models.CharField(max_length=255, unique=True),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payment.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomerExternalPaymentSystemAccount",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("unique_account_number", models.CharField(max_length=255)),
                (
                    "system_type",
                    models.CharField(
                        choices=[("d24_mercadopago", "D24 MercadoPago")], max_length=200
                    ),
                ),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("active", models.BooleanField(default=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payment.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Merchant",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("secret_key", models.CharField(max_length=200, unique=True)),
                (
                    "risk_control",
                    models.BooleanField(
                        default=False,
                        help_text="If True, Risk Limits will be checked for this merchant",
                    ),
                ),
                ("sandbox", models.BooleanField(default=False)),
                (
                    "login_users",
                    models.ManyToManyField(
                        help_text="Users, who can login to this merchant's dashboard",
                        related_name="merchants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EventLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("error", "Error"),
                            ("callback_sending_attempt", "Callback Sending Attempt"),
                            ("external_api_request", "External API Request"),
                            ("callback_retry_requested", "Callback Retry Requested"),
                            ("important", "!!! Important !!!"),
                            (
                                "transaction_actualization",
                                "Transaction Actualization (Admin)",
                            ),
                            (
                                "transaction_set_status",
                                "Transaction Set Status (Admin)",
                            ),
                            (
                                "withdrawal_stuck_in_processing",
                                "Withdrawal Stuck in Processing",
                            ),
                            ("info", "Info"),
                            (
                                "customer_redirect_received",
                                "Customer Redirect Received",
                            ),
                            (
                                "create_deposit_instruction",
                                "Create Deposit Instruction",
                            ),
                            ("revert_to_initial", "Revert to Initial Status"),
                            ("declined_by_limit", "Declined by Limit"),
                            ("debug", "Debug messages"),
                            ("declined_by_risk_list", "Declined by Risk List"),
                        ],
                        max_length=255,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("extra", models.JSONField(default=dict)),
                ("request_id", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "system_type",
                    models.CharField(
                        choices=[("d24_mercadopago", "D24 MercadoPago")], max_length=200
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payment.customer",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payment.merchant",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MerchantGroup",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "queue",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("normal", "Normal"),
                            ("low", "Low"),
                            ("service", "Service"),
                        ],
                        default="normal",
                        max_length=200,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="merchant",
            name="merchant_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="payment.merchantgroup"
            ),
        ),
        migrations.CreateModel(
            name="PaymentCardBank",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "bin",
                    models.IntegerField(
                        unique=True,
                        validators=[rozert_pay.payment.models.validate_bin],
                        verbose_name="BIN",
                    ),
                ),
                (
                    "is_virtual",
                    models.BooleanField(default=False, verbose_name="Virtual Card"),
                ),
                (
                    "is_prepaid",
                    models.BooleanField(default=False, verbose_name="Prepaid Card"),
                ),
                (
                    "raw_category",
                    models.TextField(
                        blank=True,
                        help_text="Raw from XML file",
                        null=True,
                        verbose_name="Raw Category",
                    ),
                ),
                ("remark", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bins",
                        to="payment.bank",
                    ),
                ),
            ],
            options={
                "verbose_name": "BIN",
                "ordering": ("bin",),
            },
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "system_type",
                    models.CharField(
                        choices=[("d24_mercadopago", "D24 MercadoPago")], max_length=200
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=255,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "type",
                    models.CharField(
                        choices=[("deposit", "Deposit"), ("withdrawal", "Withdrawal")],
                        max_length=20,
                    ),
                ),
                ("currency", models.CharField(max_length=3)),
                ("callback_url", models.URLField(blank=True, null=True)),
                ("redirect_url", models.URLField(blank=True, null=True)),
                (
                    "id_in_payment_system",
                    models.CharField(
                        blank=True, db_index=True, max_length=200, null=True
                    ),
                ),
                (
                    "decline_code",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "decline_reason",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("instruction", models.JSONField(blank=True, null=True)),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("check_status_until", models.DateTimeField(blank=True, null=True)),
                (
                    "external_account_id",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="payment.customer",
                    ),
                ),
                (
                    "customer_card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="payment.customercard",
                    ),
                ),
                (
                    "customer_external_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="payment.customerexternalpaymentsystemaccount",
                    ),
                ),
                (
                    "customer_instruction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payment.customerdepositinstruction",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payment.currencywallet",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("can_actualize_transaction", "Can actualize payment transaction"),
                    ("can_set_transaction_status", "Can set transaction status"),
                ],
            },
        ),
        migrations.CreateModel(
            name="OutcomingCallback",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "callback_type",
                    models.CharField(
                        choices=[
                            ("deposit_account_created", "Deposit Account Created"),
                            ("deposit_received", "Deposit Received"),
                            ("transaction_updated", "Transaction Updated"),
                        ],
                        max_length=255,
                    ),
                ),
                ("target", models.URLField()),
                ("body", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error", models.TextField(blank=True, null=True)),
                ("logs", models.TextField(blank=True, null=True)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("max_attempts", models.PositiveIntegerField(default=10)),
                ("current_attempt", models.PositiveIntegerField(default=0)),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payment.paymenttransaction",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IncomingCallback",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("body", models.TextField()),
                ("headers", models.JSONField(blank=True, default=dict)),
                ("get_params", models.JSONField(blank=True)),
                ("ip", models.GenericIPAddressField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "error_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ip_not_whitelisted", "IP not whitelisted"),
                            ("invalid_signature", "Invalid signature"),
                            ("parsing_error", "Parsing error"),
                            ("validation_error", "Validation error"),
                            ("unknown_error", "Unknown error"),
                            ("authorization_error", "Authorization error"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("error", models.TextField(blank=True, null=True)),
                ("traceback", models.TextField(blank=True, null=True)),
                (
                    "remote_transaction_status",
                    models.JSONField(
                        default=dict,
                        encoder=rozert_pay.payment.models.CustomJsonEncoder,
                    ),
                ),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payment.paymentsystem",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payment.paymenttransaction",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PaymentTransactionEventLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("error", "Error"),
                            ("callback_sending_attempt", "Callback Sending Attempt"),
                            ("external_api_request", "External API Request"),
                            ("callback_retry_requested", "Callback Retry Requested"),
                            ("important", "!!! Important !!!"),
                            (
                                "transaction_actualization",
                                "Transaction Actualization (Admin)",
                            ),
                            (
                                "transaction_set_status",
                                "Transaction Set Status (Admin)",
                            ),
                            (
                                "withdrawal_stuck_in_processing",
                                "Withdrawal Stuck in Processing",
                            ),
                            ("info", "Info"),
                            (
                                "customer_redirect_received",
                                "Customer Redirect Received",
                            ),
                            (
                                "create_deposit_instruction",
                                "Create Deposit Instruction",
                            ),
                            ("revert_to_initial", "Revert to Initial Status"),
                            ("declined_by_limit", "Declined by Limit"),
                            ("debug", "Debug messages"),
                            ("declined_by_risk_list", "Declined by Risk List"),
                        ],
                        max_length=255,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("extra", models.JSONField(default=dict)),
                ("request_id", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "incoming_callback",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payment.incomingcallback",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payment.paymenttransaction",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("credentials", models.JSONField(default=dict)),
                ("comment", models.TextField(blank=True, default="")),
                ("logs", models.TextField(blank=True, default="")),
                ("default_callback_url", models.URLField(blank=True, null=True)),
                (
                    "sandbox_finalization_delay_seconds",
                    models.PositiveIntegerField(default=60),
                ),
                ("allow_negative_balances", models.BooleanField(default=False)),
                (
                    "risk_control",
                    models.BooleanField(
                        default=False,
                        help_text="If True, Risk Limits will be checked for this wallet",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payment.merchant",
                    ),
                ),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payment.paymentsystem",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DepositAccount",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("customer_id", models.CharField(max_length=100)),
                ("unique_account_identifier", models.CharField(max_length=100)),
                ("extra", models.JSONField(blank=True, default=dict)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="payment.wallet"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="customerexternalpaymentsystemaccount",
            name="wallet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="payment.wallet"
            ),
        ),
        migrations.AddField(
            model_name="customerdepositinstruction",
            name="wallet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="payment.wallet"
            ),
        ),
        migrations.AddField(
            model_name="currencywallet",
            name="wallet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="payment.wallet"
            ),
        ),
        migrations.CreateModel(
            name="ACLGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("all_groups", models.BooleanField(default=False)),
                ("all_wallets", models.BooleanField(default=False)),
                ("all_users", models.BooleanField(default=False)),
                ("all_systems", models.BooleanField(default=False)),
                (
                    "level",
                    models.CharField(
                        choices=[("read", "Read"), ("write", "Write")],
                        default="read",
                        max_length=20,
                    ),
                ),
                ("users", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ("groups", models.ManyToManyField(to="payment.merchantgroup")),
                ("systems", models.ManyToManyField(to="payment.paymentsystem")),
                ("wallets", models.ManyToManyField(to="payment.wallet")),
            ],
        ),
        migrations.AddConstraint(
            model_name="paymenttransaction",
            constraint=models.UniqueConstraint(
                fields=("system_type", "id_in_payment_system"),
                name="unique_transaction_id_in_payment_system",
            ),
        ),
        migrations.AddConstraint(
            model_name="depositaccount",
            constraint=models.UniqueConstraint(
                fields=("wallet", "customer_id"), name="unique_customer_id_per_merchant"
            ),
        ),
        migrations.AddConstraint(
            model_name="depositaccount",
            constraint=models.UniqueConstraint(
                fields=("wallet", "unique_account_identifier"),
                name="unique_account_identifier",
            ),
        ),
        migrations.AddConstraint(
            model_name="customerexternalpaymentsystemaccount",
            constraint=models.UniqueConstraint(
                fields=("system_type", "wallet", "unique_account_number"),
                name="unique_customer_wallet",
            ),
        ),
        migrations.AddConstraint(
            model_name="customerdepositinstruction",
            constraint=models.UniqueConstraint(
                fields=("system_type", "deposit_account_number"),
                name="cusdepoins_sys_account_number",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="currencywallet",
            unique_together={("wallet", "currency")},
        ),
    ]
